apiVersion: apps/v1
kind: Deployment
metadata:
  name: pair-web
  namespace: acger
  labels:
    app: pair-web
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: pair-web
  template:
    metadata:
      labels:
        app: pair-web
    spec:
      containers:
      - name: pair-web
        image: docker.io/dk251626910/ffl-pair-web:latest
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
---

apiVersion: v1
kind: Service
metadata:
  name: pair-web
  namespace: acger
spec:
  ports:
    - port: 80
  selector:
    app: pair-web

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pair-web
  namespace: acger
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: acger-pair.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: pair-web
                port:
                  number: 80
---